Traceback (most recent call last):
  File "C:\Users\37529\Desktop\github\Game-Engine-3\Game Engine 3.py", line 47, in main
    raise NameError("123")
NameError: 123
